### ISSUE TITLE
IIIF Manifest Service

### ISSUE THREAD

**Issue by andreghattas13** [swiss-art-research-net/skkg-pipeline#74]
# EPIC: IIIF Manifest Service

We need a service to generate IIIF Manifests for the SKKG Object records and deliver them over a web server. This issue includes the design and implementation of a service architecture to generate and deliver IIIF Manifests

## IIIF Manifests pipeline

The IIIF Manifests need to be generated based on the ID/URI of an SKKG Object item. The data required for generating the manifests will be retrieved from the Triple Store. This includes:
- the images associated with an object record, along with their
	- IIIF Image API URLs*
	- metadata (image size)*
- the metadata associated with an object record
	- based on queries defined in the [field definitions](https://github.com/swiss-art-research-net/skkg-app/blob/main/src/fieldDefinitions.yml)

\* This data is not yet in the triple store

## Delivering IIIF Manifests

IIIF Manifests need to be delivered as JSON via a web server. The web server needs to serve the JSON with the appropriate headers for consuming the data in a IIIF Viewer. This includes appropriate content headers as well as CORS headers.

## Generating and Caching IIIF Manifests

The IIIF Manifests should be generated and cached on demand. If a IIIF Manifest is requested for the first time, the respective JSON should be generated by the IIIF Manifests pipeline and cached for subsequent reuse. The time period for caching can be set globally.

**Comment by fkraeutli** [comment]
[FastAPI](https://fastapi.tiangolo.com/) might be a possible framework for delivering manifests
